function [CellMeasurements, ModuleData] = ktrModule_cyto_annul(CellMeasurements,parameters, labels, AuxImages, ModuleData)
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
% KTRMODULE  measure cytoplasmic:nuclear ratio in auxiliary (fluorescent) image
%
%2020331 SL: I think this can be deleted, intermediate test of sth
% adjust KTR module to use annulus (small ring around nucleus) to estimte
% cytoplasm (as is done in Covert papers), instead of full cyto area
%
% CellMeasurements    structure with fields corresponding to cell measurements
%
% parameters          experiment data (total cells, total images, output directory)
% labels              Cell,Nuclear label matricies (labels.Cell and labels.Nucleus)
% AuxImages           images to measure
% ModuleData          extra information (current ModuleData.iter, etc.) used in measurement 
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

%Do annulus to estimate cytoplasmic area.
% 2020-01-24 Play with factor after min nuclear radius
tmp_mask = imdilate(labels.Nucleus>0,diskstrel(parameters.MinNucleusRadius*1.25)); % generates a mask from dilated nuclei (which are larger than 0) using a disk-shaped structuring element (generated by diskstrel) with the radius of 2 min nuclei (5 in most of my runs)
%change this to not overwrite cell labels???
labels.Cell = IdentifySecPropagateSubfunction(double(labels.Nucleus),zeros(size(labels.Nucleus)),tmp_mask,100); %does this actually enter annulus instead of cytoplasm into saved data? No, I think


%{
%this annulus uses min nuclear radius paramter
%Do annulus to estimate cytoplasmic area.
tmp_mask = imdilate(labels.Nucleus>0,diskstrel(parameters.MinNucleusRadius*2)); % generates a mask from dilated nuclei (which are larger than 0) using a disk-shaped structuring element (generated by diskstrel) with the radius of 2 min nuclei
labels.Cell = IdentifySecPropagateSubfunction(double(labels.Nucleus),zeros(size(labels.Nu
%}


% Make conncomp structures for nucleus, cell, and cytoplasm
nuc_cc = label2cc(labels.Nucleus,0);
cell_cc = label2cc(labels.Cell,0);
cyto_cc = cell_cc;
for i = 1:min([length(cyto_cc.PixelIdxList),length(nuc_cc.PixelIdxList)])
    if ~isempty(cyto_cc.PixelIdxList{i})
        cyto_cc.PixelIdxList{i}(ismember(cyto_cc.PixelIdxList{i},nuc_cc.PixelIdxList{i})) = [];
    end
end

% Flatfield-correct auxiliary image
for i = 1:length(AuxImages)
    if ~isempty(AuxImages{i})
        
        % STEP 1: IMAGE NORMALIZATION
        % Normalization 1: flatfield correction -> estimate range for scaling
        corr_img = flatfieldcorrect(double(AuxImages{i})-double(parameters.Flatfield{end}),double(parameters.Flatfield{i}));
        % Normalization 2: background-subtract -> assume image is pretty confluent...
        corr_img = corr_img - prctile(corr_img(:),2);        
        AuxImages{i} = corr_img;
        
        
        % STEP 2: INITIALIZE DATA
        if ~isfield(CellMeasurements,['KTR_ratio',num2str(i)])
            CellMeasurements.(['KTR_ann_ratio',num2str(i)]) =  nan(parameters.TotalCells,parameters.TotalImages,1);
            CellMeasurements.(['KTR_ann_nuc',num2str(i)]) =  nan(parameters.TotalCells,parameters.TotalImages,1);
            CellMeasurements.(['KTR_ann_cyto',num2str(i)]) = nan(parameters.TotalCells,parameters.TotalImages,1);
        end

        % STEP 3: MAKE MEASUREMENT
        for n = 1:cyto_cc.NumObjects        
            if ~isempty(nuc_cc.PixelIdxList{n})
                % (Median of nuclear and cytoplasmic compartments)
                median_n = median(AuxImages{i}(nuc_cc.PixelIdxList{n}));
                median_c = median(AuxImages{i}(cyto_cc.PixelIdxList{n}));
                % Assign measurements
                CellMeasurements.(['KTR_ann_nuc',num2str(i)])(n,ModuleData.iter) = median_n;
                CellMeasurements.(['KTR_ann_cyto',num2str(i)])(n,ModuleData.iter) = median_c;
                CellMeasurements.(['KTR_ann_ratio',num2str(i)])(n,ModuleData.iter) = median_c/median_n;
            end 
        end 
    end
end


%% OLD normalization (background modeling and subtraction)
%         tmp = corr_img;
%         tmp(imdilate(labels.Nucleus>0,diskstrel(round(parameters.MinNucleusRadius*2)))) = []; % Drop foreground objects for correction calculation
%         [~, dist1] = modebalance(tmp,2,ModuleData.BitDepth,'measure');
%         corr_img = (corr_img - dist1(1)); % Background subtract (DON'T divide)
